# Server Port (React runs on 5173, so we run Java on 8080)
server.port=8080

# PostgreSQL Database Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/ecommerce_db
spring.datasource.username=postgres
spring.datasource.password=22102004
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate (Spring Data JPA) Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
